### ISSUE TITLE
[question]: Swap pgbouncer for pgbouncer-fast-switchover

### ISSUE THREAD

**Issue by wesbragagt** [Panfactum/stack#116]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a similar question has already been asked.

### What is your question?

I'm looking into the benefits of using [pgbouncer-fast-switchover](https://github.com/awslabs/pgbouncer-fast-switchover) in order to better handle failovers. I would love to test it in the stack. Would I just need to swap the image used [here](https://github.com/Panfactum/stack/blob/main/packages/infrastructure/kube_pg_cluster/main.tf#L865) in the kube_pg_cluster for pgbouncer?

### What primary components of the stack does this relate to?

terraform

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fullykubed** [comment]
Unforutnately, you cannot just drop in [pgbouncer-fast-switchover](https://github.com/awslabs/pgbouncer-fast-switchover) as it requires a completely different configuration than the normal pg bouncer in order to take advantage of any of its benefits.

As CNPG manages the PgBouncer configuration, it would not be possible to use that image inside the Pooler CR. Instead, you'd have to set it up from scratch.

**Comment by wesbragagt** [comment]
Thank you, just wanted to understand the effort better.
