### ISSUE TITLE
[Bug]: issue with AWS cli in recommended NixOS package registry version

### ISSUE THREAD

**Issue by jlevydev** [Panfactum/stack#14]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a bug report has already been made.

### What happened?

The aws cli seems broken in the release of the NixOS package registry recommended in the docs. I've pinned back my NixOS version in the meantime but may be good to recommend a more stable version. 
![Screenshot from 2024-03-12 16-33-09](https://github.com/Panfactum/stack/assets/105033689/fcbf4182-3bc2-4c68-9e8a-d51b94575e85)

### Version

main (development branch)

### What primary components of the stack are you seeing the problem on?

nix, website

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fullykubed** [comment]
This is resolved in the last commit to the `main` branch. Please upgrade your flake.lock and try again.

**Comment by fullykubed** [comment]
For clarity, the docs do not recommend any specific NixOS package registry version (if they do, please consider that a bug and would love to see that fixed). Our devenv comes prebundled with specific versions of a few dozen utilities, the AWS CLI included. You can add additional utilities (see the docs for customizing your developer environment) from arbitrary nixpkg commits, but you shouldn't do that with the AWS CLI as we have chosen a version known to be working with the stack.

This issue is not with the AWS CLI itself but rather a bug that was introduced into devenv that adds an incorrect `PYTHONPATH` environment variable to your terminal session. The latest version of the Panfactum stack provides a fix for this.

**Comment by jlevydev** [comment]
Confirmed fixed, thanks!
