### ISSUE TITLE
[Bug]: kube_bastion module fails to apply

### ISSUE THREAD

**Issue by jlevydev** [Panfactum/stack#27]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a bug report has already been made.

### What happened?

The `kube_bastion` module fails to apply with the error below. All other modules are running the latest greatest and I believe I am on the latest greatest flake as well. Let me know what other debugging information might be helpful!
![image](https://github.com/Panfactum/stack/assets/105033689/cd5724cc-0c82-4cfe-830b-5065c6e29c44)

### Version

main (development branch)

### What primary components of the stack are you seeing the problem on?

terraform

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fullykubed** [comment]
Resolved in the latest commit.

**Comment by fullykubed** [comment]
Still occurring.

**Comment by fullykubed** [comment]
So this one was a little complex.

 Essentially what `kubernetes_manifest` does is run the equivalent of `kubectl apply` under the hood. Unfortunately, this is an _upsert_ operation for certain fields and in this case it won't delete already-present template annotations. However, the tf plan thinks that it will, and thus tf becomes confused when the returned manifest does not have annotations deleted.

This is the same behavior that occurs with the primary `metadata.annotations` for the `kubernetes_manifest` resource, and my workaround was to mark them as [computed fields](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest#computed-fields). I simply extended this pattern to the template annotations.

This resolves the issue because tf will no longer care if the returned field values differ from what was planned.
