### ISSUE TITLE
[regression]: karpenter fails to provision due to "too many requirements" error

### ISSUE THREAD

**Issue by mschnee** [Panfactum/stack#60]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a bug report has already been made.

### What happened?

A bug previously fixed in https://github.com/Panfactum/stack/compare/edge.24-06-02 has returned: too many labels causes karpenter to throw the attached error. 

I believe the issue is here: https://github.com/Panfactum/stack/blob/edge.24-06-14/packages/infrastructure/kube_karpenter_node_pools/main.tf#L302 

### Steps to Reproduce

I spun up a new environment and followed the bootstrapping guide.

I was able to remediate by manually deleting all of the keys (except for `id`) under `.spec.template.metadata.labels` (not to be confused with `.spec.metadata.labels`

### Version

main (development branch)

### Relevant log output

```shell
spec.requirements: Too many: #: must have at most 30 items
```

**Comment by fullykubed** [comment]
I have validated that this issue is real.

I do believe this is a bug in upstream Karpenter: https://github.com/aws/karpenter-provider-aws/issues/6387

I will put a fix in on our side; however, the impact is the standard labels won't be applied to the nodes either as AWS tags or kubernetes labels. I believe this may have a negative impact standards like billing, etc. 

As a result, I will add a new dedicated input to the `kube_karpenter_node_pools` module for setting the tags, but this will be a breaking change.

**Comment by fullykubed** [comment]
Fixed. Will be included in the next release.
